### ISSUE TITLE
Build Error—'There was an error parsing JSON for data.json'

### ISSUE THREAD

**Issue by prakashthangavelu** [pattern-lab/starterkit-mustache-demo#4] opened 2016-08-07 18:11 UTC
I am using Pattern Lab Node- Gulp Edition `v1.2.4` with 'staterkit-mustache-demo' on `Windows 10`.
##### Expected Behavior

Expected 'gulp patternlab:serve' to open browser with patternlab's home page
##### Actual Behavior

```
There was an error parsing JSON for data.json
{ [SyntaxError: Bad string at line 1 column 2198 of the JSON5 data. Still to read: "04-pages-05-about.ht"]
  message: 'Bad string at line 1 column 2198 of the JSON5 data. Still to read: "04-pages-05-about.ht"',
  at: 2197,
  lineNumber: 1,
  columnNumber: 2198 }
[23:08:45] 'build' errored after 240 ms
[23:08:45] TypeError: Cannot read property 'link' of undefined
    at parseDataLinksHelper (E:\UwAmp\www\learning\node-pl\node_modules\patternlab-node\core\lib\pattern_assembler.js:420:39)
    at parseDataLinks (E:\UwAmp\www\learning\node-pl\node_modules\patternlab-node\core\lib\pattern_assembler.js:450:45)
    at Object.parse_data_links (E:\UwAmp\www\learning\node-pl\node_modules\patternlab-node\core\lib\pattern_assembler.js:492:7)
    at buildPatterns (E:\UwAmp\www\learning\node-pl\node_modules\patternlab-node\core\lib\patternlab.js:264:23)
    at Object.build (E:\UwAmp\www\learning\node-pl\node_modules\patternlab-node\core\lib\patternlab.js:391:7)
    at build (E:\UwAmp\www\learning\node-pl\gulpfile.js:79:14)
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at asyncRunner (E:\UwAmp\www\learning\node-pl\node_modules\gulp\node_modules\undertaker\node_modules\bach\node_modules\async-done\index.js:36:18)
    at nextTickCallbackWith0Args (node.js:420:9)
[23:08:45] 'patternlab:build' errored after 693 ms
[23:08:45] 'patternlab:serve' errored after 733 ms
```
##### Steps to Reproduce
1. Download pre-built package and run 'npm install'
2. npm install patternengine-node-mustache
3. npm install starterkit-mustache-demo
4. gulp patternlab:loadstarterkit --kit=starterkit-mustache-demo
5. gulp patternlab:serve

**Comment by bmuenzenmeyer** [comment] 2016-08-07 18:21
Can you run the .json in question through a site like jsonlint.com and see
if there is in fact malformed .json?

**Comment by prakashthangavelu** [comment] 2016-08-07 18:32
Yes I validated the data.json in jsonlint.com, but I didn't find any error.

**Comment by bmuenzenmeyer** [comment] 2016-08-08 12:45
I've confirmed there is some bug with `data.json` link parsing in PL/Node.

The code is trying to convert 

`link.pages-about` 

into

`/patterns/04-pages-05-about\04-pages-05-about.html`

which, when stringified or put into json, is not likely valid json due to the single `\`,

**Comment by bmuenzenmeyer** [comment] 2016-08-08 12:54
@prakashthangavelu until I can get a formal fix in - you can do the following.
1. open `./node_modules/patternlab-node/core/lib/pattern_assembler.js`
2. find the following line, around 421:
   `expandedLink = patternlab.data.link[linkMatches[i].split('.')[1]];`
3. replace with
   `expandedLink = encodeURI(patternlab.data.link[linkMatches[i].split('.')[1]]);`

**Comment by prakashthangavelu** [comment] 2016-08-08 13:24
@bmuenzenmeyer thank you. Its working.

**Comment by bmuenzenmeyer** [comment] 2016-11-16 21:11
this was merged into PL Node Core and released.
Closing

**Closed as completed by bmuenzenmeyer** 2016-11-16 21:11 UTC
Labels: bug
